# Generated by Django 4.1.4 on 2022-12-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название фильма')),
                ('rating', models.CharField(max_length=30, verbose_name='Рейтинг Кинопоиск')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('file', models.CharField(max_length=30, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'хуевости',
                'verbose_name_plural': 'хуевости',
            },
        ),
    ]
