# Generated by Django 4.1.4 on 2022-12-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles_create',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterField(
            model_name='articles_create',
            name='file',
            field=models.CharField(max_length=30, verbose_name='изображение'),
        ),
    ]
